### ISSUE TITLE
🐛 [Bug] Validation not working correctly

### ISSUE THREAD

**Issue by zKoz210** [goravel/goravel#220] opened 2023-07-25 14:07 UTC
### Before feedback (在反馈之前)

- [X] I've searched the existing Issues, Discussions and Google (我已经搜索了现有的 Issues, Discussions 和 Google)
- [X] The problem can be stably reproduced (这个问题可以被稳定复现)
- [ ] The problem is generated after upgrading (问题是在升级之后产生的)

### Operating System (操作系统)

Linux

### Golang Version (Go 版本)

1.20.x

### Goravel Version (Goravel 版本)

1.12.5

### Describe The Problem (描述问题)

I add a validation for the mandatory presence of the `clinics` key - this does not work correctly:

result:

```json
{
    "Data": {
        "clinics": [
            {
                "mis_clinic_id": 611
            }
        ]
    },
    "Hello": {
        "clinics": {
            "required": "clinics is required to not be empty"
        }
    }
}
```

### Reproduction Code (复现代码或截图)

```go
func (r *UserController) Show(ctx http.Context) {
	validator, _ := ctx.Request().Validate(map[string]string{
		"clinics": "required|array",
	})

	ctx.Response().Success().Json(http.Json{
		"Hello": validator.Errors().All(),
		"Data":  ctx.Request().All(),
	})
}
```

Request:
```json
{
    "clinics": [
        {
            "id": 611
        }
    ]
}
```

**Comment by hwbrzzl** [comment] 2023-07-26 00:36
Sorry, I can't reproduce it.

<img width="1440" alt="image" src="https://github.com/goravel/goravel/assets/24771476/9309ee1b-ab23-4749-9f85-133a357f1b2e">

**Comment by zKoz210** [comment] 2023-07-26 09:03
@hwbrzzl maybe it's related to the ticket https://github.com/goravel/goravel/issues/221#issuecomment-1651282896

**Comment by hwbrzzl** [comment] 2023-07-26 09:34
Good catch, let's close this issue and move to https://github.com/goravel/goravel/issues/221.

**Closed by hwbrzzl** 2023-07-26 09:34 UTC
